### ISSUE TITLE
Creating a filter system using reactJs

### ISSUE THREAD

**Issue by anagha-chaudhari** [anagha-chaudhari/BachatAbit-E-commerce-Price-Comparison-Website#2]
Creating a filter system such as filter by category, by price, by color etc.

**Comment by Sparsh47** [comment]
Hi, 
My name is Sparsh and I think I can help you with this.
You should add a key in your data named color or category or whatever you want your data to be filtered. Then you can use filter function on your data and can show the filtered object or array in react using map function or for loop. If you need a sample code or want me to implement it in your code then let me know.

**Comment by anagha-chaudhari** [comment]
@Sparsh47 Sure, you can implement it! Thank you for helping

**Comment by Sparsh47** [comment]
So do you want me to change your whole codebase? because you have only one branch i.e. main and it only has html content. So you want me to implement it in html js only or you have another react repository that you want me to help in?

**Comment by anagha-chaudhari** [comment]
@Sparsh47 no I do not have a react repository.. Is it possible to implement it in html js only?

**Comment by Sparsh47** [comment]
I think we can do that. I'll just fork your repository and then create a PR.

**Comment by Sparsh47** [comment]
You want a separate filter component or just a filter function???

**Comment by anagha-chaudhari** [comment]
@Sparsh47 For now, just with a filtering function

**Comment by Sparsh47** [comment]
So for filtering function you don't need react. If you just want to create a function then that can be done using js also.

**Comment by anagha-chaudhari** [comment]
Oh right! you can do anyways you want. Please let me know when you start working on it. Thank you once again!
